pipeline:
  build:
    image: 'node:9.11.1-alpine'
    commands:
      - yarn install
      - yarn test
      - yarn build
  slack:
    image: plugins/slack
    webhook: slack_webhook
    channel: slack_channel
    username: slack_user
    icon_url: slack_icon
    when:
      status:
        - success
        - failure
