pipeline:
  build:
    image: 'node:9.11.1-alpine'
    commands:
      - yarn install
      - yarn test
      - yarn build
  slack:
    image: plugins/slack
    webhook: slack_webhook
    when:
      status:
        - success
        - failure
    secrets:
      - slack_webhook
