pipeline:
  build:
    image: 'node:9.11.1-alpine'
    commands:
      - yarn install
      - yarn test
      - yarn build
  docker:
    image: plugins/docker
    repo: jamesvmcewan/mce-react
    username: docker_username
    password: docker_password
    autotag: true
    secrets:
      - docker_username
      - docker_password
  slack:
    image: plugins/slack
    webhook: slack_webhook
    when:
      status:
        - success
        - failure
    secrets:
      - slack_webhook
